export const ResultData = [
    { 
        key: 1,
        index: '1', 
        task_name: '检查系统补丁安装情况', 
        task_id: '1', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 2,
        index: '2', 
        task_name: '检测系统网络', 
        task_id: '11', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '网络通信配置', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 3,
        index: '3', 
        task_name: '检查系统补丁安装情况', 
        task_id: '11', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 4,
        index: '4', 
        task_name: '检查系统补丁安装情况', 
        task_id: '1', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.36', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 5,
        index: '5', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 6,
        index: '6', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 7,
        index: '7', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.115', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 8,
        index: '8', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.125', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 9,
        index: '9', 
        task_name: '检测系统网络', 
        task_id: '31', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.25', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 10,
        index: '10', 
        task_name: '检查系统补丁安装情况', 
        task_id: '31', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.25', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 11,
        index: '11', 
        task_name: '检查系统补丁安装情况', 
        task_id: '1', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 12,
        index: '12', 
        task_name: '检测系统网络', 
        task_id: '11', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '网络通信配置', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 13,
        index: '13', 
        task_name: '检查系统补丁安装情况', 
        task_id: '11', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 14,
        index: '14', 
        task_name: '检查系统补丁安装情况', 
        task_id: '1', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.36', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 15,
        index: '15', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 16,
        index: '16', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 17,
        index: '17', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.115', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 18,
        index: '18', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.125', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 19,
        index: '19', 
        task_name: '检测系统网络', 
        task_id: '31', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.25', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 20,
        index: '20', 
        task_name: '检查系统补丁安装情况', 
        task_id: '31', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.25', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 21,
        index: '21', 
        task_name: '检查系统补丁安装情况', 
        task_id: '1', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 22,
        index: '22', 
        task_name: '检测系统网络', 
        task_id: '11', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '网络通信配置', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 23,
        index: '23', 
        task_name: '检查系统补丁安装情况', 
        task_id: '11', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 24,
        index: '24', 
        task_name: '检查系统补丁安装情况', 
        task_id: '1', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.36', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 25,
        index: '25', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 26,
        index: '26', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.15', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 27,
        index: '27', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.115', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 28,
        index: '28', 
        task_name: '检测系统网络', 
        task_id: '3', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.125', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 29,
        index: '29', 
        task_name: '检测系统网络', 
        task_id: '31', 
        target_name: '工控服务器', 
        target_ip: '192.168.1.25', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, { 
        key: 30,
        index: '30', 
        task_name: '检查系统补丁安装情况', 
        task_id: '31', 
        target_name: '数据库服务器', 
        target_ip: '192.168.1.25', 
        risk_type: '操作系统补丁安装', 
        risk_desc: 'Windows Alerter服务没有启动安全通知', 
        risk_level: '中', 
        solution: '进入【控制面板】->【操作中心】，进入【更改操作中心设置】，选择所有安全消息', 
    }, 

];